---
- name: check if sdkman exists
  stat:
    path: ~/.sdkman
  register: sdkman_install

- name: install sdkman
  when: sdkman_install.stat.exists == False
  shell: curl -s https://get.sdkman.io | bash  executable=/bin/bash

- name: install java11
  when: sdkman_install.stat.exists == True
  shell: "source {{ lookup('env','HOME') }}/.sdkman/bin/sdkman-init.sh && sdk install java 11.0.12-open"
  args:
    executable: /bin/bash
- name: install java17
  when: sdkman_install.stat.exists == True
  shell: "source {{ lookup('env','HOME') }}/.sdkman/bin/sdkman-init.sh && sdk install java 17.0.4-amzn"
  args:
    executable: /bin/bash
- name: install java18
  when: sdkman_install.stat.exists == True
  shell: "source {{ lookup('env','HOME') }}/.sdkman/bin/sdkman-init.sh && sdk install java 18.0.2.1-open"
  args:
    executable: /bin/bash
- name: install java8
  when: sdkman_install.stat.exists == True
  shell: "source {{ lookup('env','HOME') }}/.sdkman/bin/sdkman-init.sh && sdk install java 8.0.302-open"
  args:
    executable: /bin/bash
- name: install maven
  when: sdkman_install.stat.exists == True
  shell: "source {{ lookup('env','HOME') }}/.sdkman/bin/sdkman-init.sh && sdk install maven"
  args:
    executable: /bin/bash
