---
- name: Clone eclipse.jdt.ls
  git:
    repo: https://github.com/eclipse/eclipse.jdt.ls
    dest: ~/dev/eclipse/eclipse.jdt.ls
- name: Build eclipse.jdt.ls
  command: ./mvnw clean install -DskipTests
  environment:
    JAVA_HOME: /usr/lib/jvm/java-11-openjdk/
  args:
    chdir: ~/OSProjects/Neovim/eclipse/eclipse.jdt.ls

- name: Clone java-debug
  git:
    repo: https://github.com/microsoft/java-debug
    dest: ~/OSProjects/Neovim/microsoft/java-debug
- name: Build java-debug
  command: ./mvnw clean install
  environment:
    JAVA_HOME: /usr/lib/jvm/java-11-openjdk/
  args:
    chdir: ~/OSProjects/Neovim/microsoft/java-debug

- name: Clone vscode-java-test
  git:
    repo: https://github.com/microsoft/vscode-java-test
    dest: ~/OSProjects/Neovim/microsoft/vscode-java-test
    force: true  # npm commands below modify the package.json

- name: Build vscode-java-test
  command: "{{ item }}"
  environment:
    JAVA_HOME: /usr/lib/jvm/java-11-openjdk/
  args:
    chdir: ~/OSProjects/Neovim/microsoft/vscode-java-test
  loop:
    - git clean -xdff
    - npm install
    - npm run build-plugin
