---
- name: Clone eclipse.jdt.ls
  git:
    repo: https://github.com/eclipse/eclipse.jdt.ls
    dest: "{{ lookup('env','HOME') }}/OSProjects/Neovim/eclipse/eclipse.jdt.ls"



- name: Build eclipse.jdt.ls
  command: ./mvnw clean install -DskipTests
  environment:
    JAVA_HOME: "{{ lookup('env','HOME') }}/.sdkman/candidates/java/11.0.12-open"
  args:
    chdir: "{{ lookup('env','HOME') }}/OSProjects/Neovim/eclipse/eclipse.jdt.ls"
    creates: "{{ lookup('env','HOME') }}/OSProjects/Neovim/eclipse/eclipse.jdt.ls/org.eclipse.jdt.ls.product/target/repository/plugins"

- name: Clone java-debug
  git:
    repo: https://github.com/microsoft/java-debug
    dest: "{{ lookup('env','HOME') }}/OSProjects/Neovim/microsoft/java-debug"

- name: Build java-debug
  command: ./mvnw clean install
  environment:
    JAVA_HOME: "{{ lookup('env','HOME') }}/.sdkman/candidates/java/18.0.2.1-open"
  args:
    chdir: "{{ lookup('env','HOME') }}/OSProjects/Neovim/microsoft/java-debug"
    creates: "{{ lookup('env','HOME') }}/OSProjects/Neovim/microsoft/java-debug/com.microsoft.java.debug/plugin/target"

- name: Clone vscode-java-test
  git:
    repo: https://github.com/microsoft/vscode-java-test
    dest: "{{ lookup('env','HOME') }}/OSProjects/Neovim/microsoft/vscode-java-test"
    force: true  # npm commands below modify the package.json

- name: Build vscode-java-test
  command: "{{ item }}"
  environment:
    JAVA_HOME: "{{ lookup('env','HOME') }}/.sdkman/candidates/java/18.0.2.1-open"
  args:
    chdir: "{{ lookup('env','HOME') }}/OSProjects/Neovim/microsoft/vscode-java-test"
    creates: "{{ lookup('env','HOME') }}/OSProjects/Neovim/microsoft/vscode-java-test/server"
  loop:
    - git clean -xdff
    - npm install
    - npm run build-plugin
- name: Download lombok
  get_url: 
    url: https://projectlombok.org/downloads/lombok.jar
    dest: "{{ lookup('env','HOME') }}/OSProjects/Binaries/lombok.jar"

- name: Download neovim config
  git:
    repo: https://github.com/zerotwopocket/nvim.git
    dest: "{{ lookup('env','HOME') }}/.config/nvim"
    update: false

- name: Download getnf
  git:
    repo: https://github.com/ronniedroid/getnf.git
    dest: "{{ lookup('env','HOME') }}/OSProjects/getnf"
    update: false

- name: Build getnf
  command: ./install.sh
  args:
    chdir: "{{ lookup('env','HOME') }}/OSProjects/getnf"
    executable: /bin/bash
