---
- name: install zsh
  become: yes
  apt:
    name: zsh
  tags: apt

- name: change shell to zsh
  become: yes
  user:
    name: "{{ the_user }}"
    shell: /usr/bin/zsh


- name: check zsh conf exists
  stat:
    path: ~/.oh-my-zsh
  register: oh_my_stats

- name: install oh-my-zsh
  shell: curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh | sh executable=/usr/bin/sh
  when: oh_my_stats.stat.exists == False
  become: yes

- name: install zsh-autosuggest
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: ~/.oh-my-zsh/plugins/zsh-autosuggestions
