---
- name: Detect nvm
  stat:
    path: ~/.nvm
  register: nvm_install

- name: Install nvm if not exists
  when: nvm_install.stat.exists == False
  shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash executable=/bin/bash

- name: Install node via nvm
  when: nvm_install.stat.exists == True
  shell: "source {{ lookup('env','HOME') }}/.nvm/nvm.sh && nvm install --lts"
  args:
    executable: /bin/bash
