---
- name: update cache
  become: yes
  apt:
    update_cache: yes
- name: upgrade packages
  become: yes
  apt:
    name: "*"
    state: latest
- name: remove unused packages
  become: yes
  apt:
    autoremove: yes
