---
- name: update cache
  become: yes
  apt:
    update_cache: yes
  tags: apt, docker

- name: upgrade packages
  become: yes
  apt:
    name: "*"
    state: latest
  tags: apt

- name: remove unused packages
  become: yes
  apt:
    autoremove: yes
  tags: apt

- name: install tree
  become: yes
  apt:
    name: tree
  tags: apt

- name: install zip
  become: yes
  package:
    name: zip
  tags: apt

- name: install unzip
  become: yes
  package:
    name: unzip
  tags: apt

- name: check if binaries dir exists
  become: no
  stat:
    path: ~/OSProjects/Binaries
  register: osproject_bin_exists
  
- name: create os project binaries directory
  shell: mkdir -p ~/OSProjects/Binaries
  when: osproject_bin_exists.stat.exists == False
  
- name: check if homebrew exists
  become: no
  stat:
    path: /home/linuxbrew
  register: linuxbrew_exists
  tags:
    - brew
    - package-manager

- name: install homebrew
  become: no
  shell: /bin/bash -c "$(curl -fsSL http://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  args:
    executable: /bin/bash
  when: linuxbrew_exists.stat.exists == False
  tags: brew

- name: install ripgrep
  become: no
  shell: /home/linuxbrew/.linuxbrew/bin/brew install ripgrep
  when: linuxbrew_exists.stat.exists == True
  tags: brew

- name: install fzf
  become: no
  shell: /home/linuxbrew/.linuxbrew/bin/brew install fzf
  when: linuxbrew_exists.stat.exists == True
  tags: brew

- name: install httpie
  become: no
  shell: /home/linuxbrew/.linuxbrew/bin/brew install httpie
  when: linuxbrew_exists.stat.exists == True
  tags: brew

- name: install vagrant
  become: no
  shell: /home/linuxbrew/.linuxbrew/bin/brew install vagrant
  when: linuxbrew_exists.stat.exists == True
  tags: brew

- name: install xclip for clipboard
  become: yes
  package:
    name: xclip
  tags: apt

- name: install fontconfig
  become: yes
  package:
    name: fontconfig
  tags: apt

- name: install fd
  become: yes
  package:
    name: fd-find
  tags: apt

- name: install tmux
  become: yes
  package:
    name: tmux
  tags: apt

- name: install maim (screenshot)
  become: yes
  package:
    name: maim
  tags: apt

- name: install install pynvim
  become: no
  shell: python3 -m pip install --user --upgrade pynvim
  tags: nvim

- name: install tree-sitter
  become: no
  shell: pip3 install tree-sitter
